table:
  name: v_meeting_welcomeSettings
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: meeting_welcomeSettings
  custom_root_fields: {}
select_permissions:
  - role: bbb_client
    permission:
      columns:
        - modOnlyMessage
        - welcomeMsg
        - welcomeMsgTemplate
      filter:
        meetingId:
          _eq: X-Hasura-MeetingId
